#!/usr/bin/env python3
"""Plot the matched d_conv=4 stateful/stateless residual-Mamba rollouts.

The four input JSON files are generated by
``eval_resmamba_res2_v20_dc4_stateful_stateless.slurm``.  Each includes a
frozen vanilla-GraphCast rollout evaluated on the exact same 32 anchors.
"""
from __future__ import annotations

import argparse
import json
from pathlib import Path

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import xarray as xr


ROOT = Path(__file__).resolve().parents[2]
STATEFUL_ROOT = ROOT / "artifacts/checkpoints/7_years/resmamba_res2_v20_dinner16_layers2_loop_dconv_sweep_20k"
STATELESS_ROOT = ROOT / "artifacts/checkpoints/7_years/resmamba_res2_v20_dconv4_stateless_ablation_20k"
DEFAULT_OUTPUT_DIR = ROOT / "plots/analyze_models/images/resolution_eval/resmamba_res2_v20_dc4_stateful_vs_stateless"
DEFAULT_DATA_DIR = ROOT / "plots/analyze_models/data/resolution_eval/resmamba_res2_v20_dc4_stateful_vs_stateless"

VARIABLE_WEIGHTS = {
    "2m_temperature": 1.0,
    "10m_u_component_of_wind": 0.1,
    "10m_v_component_of_wind": 0.1,
    "mean_sea_level_pressure": 0.1,
    "total_precipitation_6hr": 0.1,
}


def level_key(level: float) -> int | float:
    return int(level) if float(level).is_integer() else float(level)


def weighted_mse_improvement(evaluation: dict, scales: xr.Dataset) -> np.ndarray:
    """GraphCast-weighted normalized-MSE improvement over the JSON baseline."""
    channels = evaluation["per_channel_per_step"]
    levels = np.asarray(scales.level.values, dtype=float)
    level_weights = {level_key(level): level / levels.mean() for level in levels}
    baseline_total = full_total = None
    for variable, scale_da in scales.data_vars.items():
        variable_weight = VARIABLE_WEIGHTS.get(variable, 1.0)
        if "level" in scale_da.dims:
            baseline_var = full_var = None
            count = 0
            for level in levels:
                key = f"{variable}_level{level_key(level)}"
                if key not in channels:
                    continue
                item = channels[key]
                scale = float(scale_da.sel(level=level).values)
                factor = level_weights[level_key(level)] / scale**2
                baseline = np.square(np.asarray(item["rmse_baseline"], dtype=float)) * factor
                full = np.square(np.asarray(item["rmse_full"], dtype=float)) * factor
                baseline_var = baseline if baseline_var is None else baseline_var + baseline
                full_var = full if full_var is None else full_var + full
                count += 1
            if not count:
                continue
            baseline_term = variable_weight * baseline_var / count
            full_term = variable_weight * full_var / count
        elif variable in channels:
            item = channels[variable]
            scale = float(scale_da.values)
            baseline_term = variable_weight * np.square(np.asarray(item["rmse_baseline"], dtype=float)) / scale**2
            full_term = variable_weight * np.square(np.asarray(item["rmse_full"], dtype=float)) / scale**2
        else:
            continue
        baseline_total = baseline_term if baseline_total is None else baseline_total + baseline_term
        full_total = full_term if full_total is None else full_total + full_term
    if baseline_total is None:
        raise ValueError("No compatible channels found for weighted metric.")
    return 100.0 * (1.0 - full_total / baseline_total)


def input_specs() -> list[dict[str, object]]:
    return [
        {"label": "Stateful Mamba", "feedback": "open", "stateful": True,
         "path": STATEFUL_ROOT / "resmamba_res2_v20_k14_di16_l2_dc4_open_20000steps/eval/cold_bp_zero_matched/step16000.json"},
        {"label": "Stateless Mamba", "feedback": "open", "stateful": False,
         "path": STATELESS_ROOT / "resmamba_res2_v20_k14_di16_l2_dc4_open_stateless_20000steps/eval/cold_bp_zero_matched/step20000.json"},
        {"label": "Stateful Mamba", "feedback": "closed", "stateful": True,
         "path": STATEFUL_ROOT / "resmamba_res2_v20_k14_di16_l2_dc4_closed_sg_20000steps/eval/cold_full_zero_matched/step16000.json"},
        {"label": "Stateless Mamba", "feedback": "closed", "stateful": False,
         "path": STATELESS_ROOT / "resmamba_res2_v20_k14_di16_l2_dc4_closed_sg_stateless_20000steps/eval/cold_full_zero_matched/step20000.json"},
    ]


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output-dir", type=Path, default=DEFAULT_OUTPUT_DIR)
    parser.add_argument("--data-dir", type=Path, default=DEFAULT_DATA_DIR)
    parser.add_argument("--stats-dir", type=Path, default=ROOT / "data/graphcast/graphcast/stats")
    args = parser.parse_args()

    scales = xr.open_dataset(args.stats_dir / "diffs_stddev_by_level.nc")
    records, groups = [], {"open": [], "closed": []}
    for spec in input_specs():
        path = spec["path"]
        if not path.is_file():
            raise FileNotFoundError(f"Missing evaluation output: {path}")
        with path.open(encoding="utf-8") as f:
            evaluation = json.load(f)
        temperature = evaluation["per_channel_per_step"]["2m_temperature"]
        baseline = np.asarray(temperature["rmse_baseline"], dtype=float)
        full = np.asarray(temperature["rmse_full"], dtype=float)
        improvement = weighted_mse_improvement(evaluation, scales)
        hours = 6 * np.arange(1, len(full) + 1)
        item = {**spec, "baseline": baseline, "full": full, "improvement": improvement, "hours": hours,
                "n_samples": evaluation["n_samples"]}
        groups[str(spec["feedback"])].append(item)
        for hour, base, value, gain in zip(hours, baseline, full, improvement):
            records.append({
                "feedback": spec["feedback"], "model": spec["label"], "stateful": spec["stateful"],
                "lead_hours": hour, "lead_days": hour / 24, "vanilla_gc_2m_temperature_rmse_k": base,
                "model_2m_temperature_rmse_k": value, "weighted_mse_improvement_pct": gain,
                "n_samples": evaluation["n_samples"], "checkpoint": evaluation["ckpt"], "eval_json": str(path),
            })

    colors = {True: "#D55E00", False: "#0072B2"}
    fig, axes = plt.subplots(2, 2, figsize=(13, 9), sharex=True)
    for row, feedback in enumerate(("open", "closed")):
        items = groups[feedback]
        reference = items[0]["baseline"]
        if not all(np.allclose(reference, item["baseline"], rtol=1e-7, atol=1e-8) for item in items[1:]):
            raise ValueError(f"Vanilla GC baselines differ across {feedback} evaluations.")
        ax_rmse, ax_gain = axes[row]
        hours = items[0]["hours"]
        ax_rmse.plot(hours / 24, reference, color="0.2", lw=2.5, label="Frozen vanilla GC")
        for item in items:
            ax_rmse.plot(hours / 24, item["full"], color=colors[item["stateful"]], lw=2.3,
                         label=f"{item['label']} (step {Path(item['path']).stem.removeprefix('step')})")
            ax_gain.plot(hours / 24, item["improvement"], color=colors[item["stateful"]], lw=2.3,
                         label=item["label"])
        feedback_label = "baseline-feedback" if feedback == "open" else "closed-loop feedback"
        ax_rmse.set(title=f"{feedback_label}: absolute 2 m temperature error", ylabel="RMSE (K)")
        ax_gain.set(title=f"{feedback_label}: improvement over vanilla GC", ylabel="weighted normalized-MSE improvement (%)")
        ax_gain.axhline(0, color="0.2", lw=0.8)
        for ax in (ax_rmse, ax_gain):
            ax.grid(alpha=0.3)
            ax.legend(fontsize=9)
            ax.set_xlim(0.25, 10)
            ax.set_xticks(np.arange(1, 11))
    for ax in axes[-1]:
        ax.set_xlabel("lead time (days)")
    fig.suptitle("d_conv=4 residual-Mamba: state carried vs reset each rollout call\nmatched cold evaluation, zero residual state, 32 held-out anchors", fontsize=14)
    fig.tight_layout()
    args.output_dir.mkdir(parents=True, exist_ok=True)
    output = args.output_dir / "resmamba_res2_v20_dc4_stateful_vs_stateless_cold_rollout.png"
    fig.savefig(output, dpi=180, bbox_inches="tight")
    plt.close(fig)

    args.data_dir.mkdir(parents=True, exist_ok=True)
    summary = args.data_dir / "resmamba_res2_v20_dc4_stateful_vs_stateless_cold_rollout.csv"
    pd.DataFrame(records).to_csv(summary, index=False)
    print(f"Saved plot: {output}")
    print(f"Saved summary: {summary}")


if __name__ == "__main__":
    main()
