#!/usr/bin/env python3
"""Plot the matched d_conv=4 stateful/stateless residual-Mamba rollouts.

The four input JSON files are generated by
``eval_resmamba_res2_v20_dc4_stateful_stateless.slurm``.  Each includes a
frozen vanilla-GraphCast rollout evaluated on the exact same 32 anchors.
"""
from __future__ import annotations

import argparse
import json
from pathlib import Path

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import xarray as xr


ROOT = Path(__file__).resolve().parents[2]
STATEFUL_ROOT = ROOT / "artifacts/checkpoints/7_years/resmamba_res2_v20_dinner16_layers2_loop_dconv_sweep_20k"
STATELESS_ROOT = ROOT / "artifacts/checkpoints/7_years/resmamba_res2_v20_dconv4_stateless_ablation_20k"
DEFAULT_OUTPUT_DIR = ROOT / "plots/analyze_models/images/resolution_eval/resmamba_res2_v20_dc4_stateful_vs_stateless"
DEFAULT_DATA_DIR = ROOT / "plots/analyze_models/data/resolution_eval/resmamba_res2_v20_dc4_stateful_vs_stateless"

VARIABLE_WEIGHTS = {
    "2m_temperature": 1.0,
    "10m_u_component_of_wind": 0.1,
    "10m_v_component_of_wind": 0.1,
    "mean_sea_level_pressure": 0.1,
    "total_precipitation_6hr": 0.1,
}


def level_key(level: float) -> int | float:
    return int(level) if float(level).is_integer() else float(level)


def weighted_mse_improvement(evaluation: dict, scales: xr.Dataset) -> np.ndarray:
    """GraphCast-weighted normalized-MSE improvement over the JSON baseline."""
    channels = evaluation["per_channel_per_step"]
    levels = np.asarray(scales.level.values, dtype=float)
    level_weights = {level_key(level): level / levels.mean() for level in levels}
    baseline_total = full_total = None
    for variable, scale_da in scales.data_vars.items():
        variable_weight = VARIABLE_WEIGHTS.get(variable, 1.0)
        if "level" in scale_da.dims:
            baseline_var = full_var = None
            count = 0
            for level in levels:
                key = f"{variable}_level{level_key(level)}"
                if key not in channels:
                    continue
                item = channels[key]
                scale = float(scale_da.sel(level=level).values)
                factor = level_weights[level_key(level)] / scale**2
                baseline = np.square(np.asarray(item["rmse_baseline"], dtype=float)) * factor
                full = np.square(np.asarray(item["rmse_full"], dtype=float)) * factor
                baseline_var = baseline if baseline_var is None else baseline_var + baseline
                full_var = full if full_var is None else full_var + full
                count += 1
            if not count:
                continue
            baseline_term = variable_weight * baseline_var / count
            full_term = variable_weight * full_var / count
        elif variable in channels:
            item = channels[variable]
            scale = float(scale_da.values)
            baseline_term = variable_weight * np.square(np.asarray(item["rmse_baseline"], dtype=float)) / scale**2
            full_term = variable_weight * np.square(np.asarray(item["rmse_full"], dtype=float)) / scale**2
        else:
            continue
        baseline_total = baseline_term if baseline_total is None else baseline_total + baseline_term
        full_total = full_term if full_total is None else full_total + full_term
    if baseline_total is None:
        raise ValueError("No compatible channels found for weighted metric.")
    return 100.0 * (1.0 - full_total / baseline_total)


def input_specs(*, swa_4k_12k: bool = False) -> list[dict[str, object]]:
    if swa_4k_12k:
        return [
            {"label": "Stateful Mamba SWA 4k–12k", "feedback": "open", "stateful": True,
             "path": STATEFUL_ROOT / "resmamba_res2_v20_k14_di16_l2_dc4_open_20000steps/eval/cold_bp/swa_step4k-12k.json"},
            {"label": "Stateless Mamba SWA 4k–12k", "feedback": "open", "stateful": False,
             "path": STATELESS_ROOT / "resmamba_res2_v20_k14_di16_l2_dc4_open_stateless_20000steps/eval/cold_bp_zero_matched/swa_step4k-12k.json"},
        ]
    return [
        {"label": "Stateful Mamba", "feedback": "open", "stateful": True,
         "path": STATEFUL_ROOT / "resmamba_res2_v20_k14_di16_l2_dc4_open_20000steps/eval/cold_bp_zero_matched/step16000.json"},
        {"label": "Stateless Mamba", "feedback": "open", "stateful": False,
         "path": STATELESS_ROOT / "resmamba_res2_v20_k14_di16_l2_dc4_open_stateless_20000steps/eval/cold_bp_zero_matched/step20000.json"},
        {"label": "Stateful Mamba", "feedback": "closed", "stateful": True,
         "path": STATEFUL_ROOT / "resmamba_res2_v20_k14_di16_l2_dc4_closed_sg_20000steps/eval/cold_full_zero_matched/step16000.json"},
        {"label": "Stateless Mamba", "feedback": "closed", "stateful": False,
         "path": STATELESS_ROOT / "resmamba_res2_v20_k14_di16_l2_dc4_closed_sg_stateless_20000steps/eval/cold_full_zero_matched/step20000.json"},
    ]


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output-dir", type=Path, default=DEFAULT_OUTPUT_DIR)
    parser.add_argument("--data-dir", type=Path, default=DEFAULT_DATA_DIR)
    parser.add_argument("--stats-dir", type=Path, default=ROOT / "data/graphcast/graphcast/stats")
    parser.add_argument(
        "--allow-missing",
        action="store_true",
        help="Render available curves only and label the result as partial.",
    )
    parser.add_argument(
        "--swa-4k-12k",
        action="store_true",
        help="Compare the open-loop stateful and stateless 4k--12k SWA checkpoints.",
    )
    args = parser.parse_args()

    scales = xr.open_dataset(args.stats_dir / "diffs_stddev_by_level.nc")
    records, groups, missing = [], {"open": [], "closed": []}, []
    for spec in input_specs(swa_4k_12k=args.swa_4k_12k):
        path = spec["path"]
        if not path.is_file():
            if not args.allow_missing:
                raise FileNotFoundError(f"Missing evaluation output: {path}")
            missing.append(f"{spec['label']} ({spec['feedback']} loop)")
            continue
        with path.open(encoding="utf-8") as f:
            evaluation = json.load(f)
        temperature = evaluation["per_channel_per_step"]["2m_temperature"]
        baseline = np.asarray(temperature["rmse_baseline"], dtype=float)
        full = np.asarray(temperature["rmse_full"], dtype=float)
        improvement = weighted_mse_improvement(evaluation, scales)
        hours = 6 * np.arange(1, len(full) + 1)
        item = {**spec, "baseline": baseline, "full": full, "improvement": improvement, "hours": hours,
                "n_samples": evaluation["n_samples"]}
        groups[str(spec["feedback"])].append(item)
        for hour, base, value, gain in zip(hours, baseline, full, improvement):
            records.append({
                "feedback": spec["feedback"], "model": spec["label"], "stateful": spec["stateful"],
                "lead_hours": hour, "lead_days": hour / 24, "vanilla_gc_2m_temperature_rmse_k": base,
                "model_2m_temperature_rmse_k": value, "weighted_mse_improvement_pct": gain,
                "n_samples": evaluation["n_samples"], "checkpoint": evaluation["ckpt"], "eval_json": str(path),
            })

    colors = {True: "#D55E00", False: "#0072B2"}
    feedbacks = ("open",) if args.swa_4k_12k else ("open", "closed")
    if args.swa_4k_12k:
        fig, axes = plt.subplots(1, 2, figsize=(13, 4.8), sharex=True)
        axes = np.asarray([axes])
    else:
        fig, axes = plt.subplots(2, 2, figsize=(13, 9), sharex=True)
    baseline_spreads = []
    for row, feedback in enumerate(feedbacks):
        items = groups[feedback]
        if not items:
            for ax in axes[row]:
                ax.set_axis_off()
                ax.text(0.5, 0.5, f"No completed {feedback}-loop evaluation", ha="center", va="center")
            continue
        baselines = np.asarray([item["baseline"] for item in items])
        reference = baselines.mean(axis=0)
        spread = float(np.max(np.ptp(baselines, axis=0)))
        baseline_spreads.append(spread)
        if spread > 0.01:
            raise ValueError(
                f"Vanilla GC baselines differ materially across {feedback} "
                f"evaluations (max spread {spread:.4f} K).")
        ax_rmse, ax_gain = axes[row]
        hours = items[0]["hours"]
        baseline_label = "Frozen vanilla GC"
        if spread > 0:
            baseline_label += " (mean recorded reference)"
        ax_rmse.plot(hours / 24, reference, color="0.2", lw=2.5, label=baseline_label)
        for item in items:
            ax_rmse.plot(hours / 24, item["full"], color=colors[item["stateful"]], lw=2.3,
                         label=f"{item['label']} (step {Path(item['path']).stem.removeprefix('step')})")
            ax_gain.plot(hours / 24, item["improvement"], color=colors[item["stateful"]], lw=2.3,
                         label=item["label"])
        feedback_label = "baseline-feedback" if feedback == "open" else "closed-loop feedback"
        ax_rmse.set(title=f"{feedback_label}: absolute 2 m temperature error", ylabel="RMSE (K)")
        ax_gain.set(title=f"{feedback_label}: improvement over vanilla GC", ylabel="weighted normalized-MSE improvement (%)")
        ax_gain.axhline(0, color="0.2", lw=0.8)
        for ax in (ax_rmse, ax_gain):
            ax.grid(alpha=0.3)
            ax.legend(fontsize=9)
            ax.set_xlim(0.25, 10)
            ax.set_xticks(np.arange(1, 11))
    for ax in axes[-1]:
        ax.set_xlabel("lead time (days)")
    if args.swa_4k_12k:
        title = (
            "d_conv=4 residual-Mamba: stateful vs stateless SWA (4k--12k)\n"
            "open-loop matched cold evaluation, zero residual state, 32 held-out anchors"
        )
    else:
        title = (
            "d_conv=4 residual-Mamba: state carried vs reset each rollout call\n"
            "matched cold evaluation, zero residual state, 32 held-out anchors"
        )
    if missing:
        title += "\nPARTIAL: pending " + "; ".join(missing)
    if any(spread > 0 for spread in baseline_spreads):
        title += f"\nRecorded vanilla-reference spread ≤ {max(baseline_spreads):.4f} K"
    fig.suptitle(title, fontsize=14)
    fig.tight_layout()
    args.output_dir.mkdir(parents=True, exist_ok=True)
    suffix = "_swa_step4k-12k" if args.swa_4k_12k else ""
    if missing:
        suffix += "_partial"
    output = args.output_dir / f"resmamba_res2_v20_dc4_stateful_vs_stateless_cold_rollout{suffix}.png"
    fig.savefig(output, dpi=180, bbox_inches="tight")
    plt.close(fig)

    args.data_dir.mkdir(parents=True, exist_ok=True)
    summary = args.data_dir / f"resmamba_res2_v20_dc4_stateful_vs_stateless_cold_rollout{suffix}.csv"
    pd.DataFrame(records).to_csv(summary, index=False)
    print(f"Saved plot: {output}")
    print(f"Saved summary: {summary}")


if __name__ == "__main__":
    main()
